### ISSUE TITLE
cannot handle some scenarios

### ISSUE THREAD

**Issue by KatnissY** [shariqiqbal2810/MAAC#16]
hello，I try to run your code in simple_reference and simpel_world_com. However, the code reported error.  Can MAAC deal with the both physical actions and communication actions scenairos？

**Comment by shariqiqbal2810** [comment]
Hello,
The code was not written to support scenarios with both physical actions and communication capability within the same agent. In order to support this, one would need to implement multi-discrete policies (i.e. policies that output multiple categorical distributions). I would welcome a contribution to this repo if you are interested in implementing it.
